version: '3'
services: 
    getcodedone:
        stdin_open: true
        tty: true 
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: npm run start
        container_name: getcodedone
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/getcodedone
            - /getcodedone/node_modules