version: '3'
services: 
    getcodedone:
        stdin_open: true
        tty: true 
        build: .
        container_name: getcodedone
        ports:
            - "${PORT}:${PORT}"
        environment:
            - PORT=${PORT}
        volumes: 
            - ./:/getcodedone
            - /getcodedone/node_modules